export const Tracedata = {
    google: [{
        name: 'GA代码',
        key: 'ga_code',
    }, {
        name: 'GTM代码',
        key: 'head_code',
    }, {
        name: '',
        key: 'body_code',
    }, {
        name: '注册代码',
        key: 'register_code',
    }, {
        name: '购物车代码',
        key: 'cart_code',
    }, {
        name: '客服代码',
        key: 'customer_service_code',
    }, {
        name: '询盘转化',
        key: 'inquiry_code',
    }, {
        name: '交易转化',
        key: 'deal_code',
    }, ],
    facabook: [{
        name: '头部代码',
        key: 'head_code',
    }, {
        name: '底部代码',
        key: 'foot_code',
    }, {
        name: '注册代码',
        key: 'register_code',
    }, {
        name: '购物车代码',
        key: 'cart_code',
    }, {
        name: '客服代码',
        key: 'customer_service_code',
    }, {
        name: '询盘转化',
        key: 'inquiry_code',
    }, {
        name: '交易转化',
        key: 'deal_code',
    }, ],
    service: [{
        name: '在线客服代码',
        key: 'online_customer_service_code',
    }, ]

}